config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  devise_scope :user do
    # sessions
    post '/users/update_retirement_year', to: 'users/registrations#update_retirement_year'
  end

  resources :dashboard
  resources :accounts

  # Added
  post '/accounts/create', to: 'accounts#create'
  post '/accounts/update', to: 'accounts#update'

end

app/views/layouts/application.html.erb
<div class= "navbar">
  <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Dashboard', dashboard_index_path, :class => 'navbar-link' %> |
      <% if current_user.accounts.present? %>
        <%= link_to 'Adjust retirement variables', edit_account_path(current_user.id), :class => 'navbar-link' %> |
      <% end %>
      <%= link_to 'Adjust account settings', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
</div>
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalFinance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>